name: ld29_vers_la_lumiere
version: 0.1.0-dev
author: david bernard
description: "My game for Ludum Dare 29: a runner in first person view."
homepage: https://davidB.github.io/ld29_vers_la_lumiere
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: https://github.com/davidB/ld29_vers_la_lumiere
dependencies:
  asset_pack:
    git: https://github.com/johnmccutchan/asset_pack.git
  browser: any
  crypto: any
  dartemis: '>=0.6.0'
  dartemis_toolbox:
    git: https://github.com/davidB/dartemis_toolbox.git
    version: '0.6.0-dev'
  event_bus: '>=0.2.4'
  game_loop:
    git:
      ref: davidB
      url: https://github.com/davidB/game_loop.git
  glf:
    git:
      ref: ld29
      url: https://github.com/davidB/glf.git
  html_toolbox:
    version: '>=0.3.0-dev'
    git: https://github.com/davidB/html_toolbox.git
  intl: any
  js: any
  logging: any
  simple_audio:
    git: https://github.com/johnmccutchan/simpleaudio.git
    version: '>=0.9.0'
  vector_math: '>=1.3.0'
dev_dependencies:
  unittest: any

dependency_overrides:
  html_toolbox:
    path: ../html_toolbox
  glf:
    path: ../glf
  dartemis_toolbox:
    path: ../dartemis_toolbox